server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: iam-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  access-token-expiry-ms: 3600000      # 1 hour
  refresh-token-expiry-ms: 2592000000  # 30 days

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
